# OBSOLETE: use restore.sh with restore-cmd.sh !
apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-restore
  namespace: smartemission
spec:
  parallelism: 1
  backoffLimit: 0
  template:
    metadata:
      name: influxdb-restore
    spec:
      containers:
        - name: influx
          image: "influxdb:1.5.3"
          command: ["/bin/sh"]
          args: ["-c", "influxd restore -metadir /var/lib/influxdb/meta -database smartemission -datadir /var/lib/influxdb/data /backup/influxdb/"]
          volumeMounts:
          - mountPath: /var/lib/influxdb
            name: influx
          - mountPath: /backup
            readOnly: true
            name: backup
      volumes:
        - name: backup
          persistentVolumeClaim:
            claimName: influxdb-backup-influxdb-0
        - name: influx
          persistentVolumeClaim:
            claimName: influxdb-storage-influxdb-0
      restartPolicy: Never
