apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: influxdb
  namespace: smartemission
spec:
  selector:
    matchLabels:
      app: influxdb
  serviceName: "influxdb"
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: influxdb
        image: influxdb:1.5.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
  volumeClaimTemplates:
  - metadata:
      name: influxdb-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default
      resources:
        requests:
          storage: 5Gi