apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: influxdb
  namespace: smartemission
spec:
  selector:
    matchLabels:
      app: influxdb
  serviceName: "influxdb"
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: influxdb
        image: influxdb:1.6.1
        env:
          - name: INFLUXDB_DB
            value: smartemission
          - name: INFLUXDB_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: influxdb
                key: username
          - name: INFLUXDB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: influxdb
                key: password
          - name: INFLUXDB_READ_USER
            valueFrom:
              secretKeyRef:
                name: influxdb-reader
                key: username
          - name: INFLUXDB_READ_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: influxdb-reader
                key: password
          - name: INFLUXDB_WRITE_USER
            valueFrom:
              secretKeyRef:
                name: influxdb-writer
                key: username
          - name: INFLUXDB_WRITE_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: influxdb-writer
                key: password
          - name: INFLUXDB_DATA_INDEX_VERSION
            value: tsi1
          - name: INFLUXDB_HTTP_AUTH_ENABLED
            value: "true"
        ports:
        - containerPort: 8086
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-storage
        - mountPath: /backup
          name: influxdb-backup
  volumeClaimTemplates:
  - metadata:
      name: influxdb-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: influxdb-backup
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default
      resources:
        requests:
          storage: 2Gi
