apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dc-airsenseur
  namespace: collectors
spec:
  selector:
    matchLabels:
      app: dc-airsenseur
  serviceName: "dc-airsenseur"
  replicas: 1
  template:
    metadata:
      labels:
        app: dc-airsenseur
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: influxdb
        image: influxdb:1.5.3
        env:
          - name: INFLUXDB_DB
            value: airsenseur
          - name: INFLUXDB_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: dc-airsenseur-admin
                key: username
          - name: INFLUXDB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dc-airsenseur-admin
                key: password
          - name: INFLUXDB_READ_USER
            valueFrom:
              secretKeyRef:
                name: dc-airsenseur-reader
                key: username
          - name: INFLUXDB_READ_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dc-airsenseur-reader
                key: password
          - name: INFLUXDB_WRITE_USER
            valueFrom:
              secretKeyRef:
                name: dc-airsenseur-writer
                key: username
          - name: INFLUXDB_WRITE_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dc-airsenseur-writer
                key: password
          - name: INFLUXDB_DATA_INDEX_VERSION
            value: tsi1
          - name: INFLUXDB_HTTP_AUTH_ENABLED
            value: "true"
        ports:
        - containerPort: 8086
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: dc-airsenseur-storage
  volumeClaimTemplates:
  - metadata:
      name: dc-airsenseur-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default
      resources:
        requests:
          storage: 50Gi