apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: pdok-smartemission-nl
  namespace: smartemission
spec:
  secretName: pdok-smartemission-nl-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pdok.smartemission.nl
  dnsNames:
  - pdok.smartemission.nl
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - pdok.smartemission.nl