kind: Service
apiVersion: v1
metadata:
  name: dc-airsenseur
  namespace: collectors
  labels:
    app: dc-airsenseur
spec:
  type: LoadBalancer
  ports:
  - port: 8086
  selector:
    app: dc-airsenseur