apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smartapp-deployment
  namespace: smartemission
  labels:
    app: smartapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartapp
  template:
    metadata:
      labels:
        app: smartapp
    spec:
      containers:
      - name: smartapp
        image: smartemission/se-smartapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: smartapp-service
  namespace: smartemission
  labels:
    app: smartapp
spec:
  ports:
  - port: 80
  selector:
    app: smartapp