apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sosemu-deployment
  namespace: smartemission
  labels:
    app: sosemu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sosemu
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: sosemu
    spec:
      containers:
      - name: sosemu
        image: smartemission/se-sosemu:latest
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 30
          timeoutSeconds: 5
        env:
          - name: SOSEMU_DB_HOST
            value: "postgres"
          - name: SOSEMU_DB_PORT
            value: "5432"
          - name: SOSEMU_DB_NAME
            value: "gis"
          - name: SOSEMU_DB_SCHEMA
            value: "smartem_rt"
          - name: SOSEMU_DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres
                key: username
          - name: SOSEMU_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
        ports:
        - containerPort: 80