apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: geoserver-deployment
  namespace: smartemission
  labels:
    app: geoserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geoserver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: geoserver
    spec:
      containers:
      - name: geoserver
        image: smartemission/se-geoserver:1.0.0
        livenessProbe:
          httpGet:
            path: /geoserver/web/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /geoserver/web/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        env:
          - name: GS_USERNAME
            valueFrom:
              secretKeyRef:
                name: geoserver
                key: username
          - name: GS_PASSWD
            valueFrom:
              secretKeyRef:
                name: geoserver
                key: password
          - name: DB_HOSTNAME
            value: "postgres"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres
                key: username
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: PROXY_BASE_URL
            value: "https://pdok.smartemission.nl/geoserver/"
        ports:
        - containerPort: 8080