apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-logging-config
  namespace: monitoring
data:
  elasticsearch.yml: |
    cluster.name: elasticsearch-logging
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.zen.ping.unicast.hosts: elasticsearch-logging
    discovery.zen.minimum_master_nodes: 1
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    xpack.license.self_generated.type: basic
  ES_JAVA_OPTS: -Xms2250m -Xmx2250m