apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: monitoring
  labels:
    app: elasticsearch-logging
spec:
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
  selector:
    app: elasticsearch-logging