apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-logging
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: elasticsearch-logging
  serviceName: "elasticsearch-logging"
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticsearch-logging
    spec:
      serviceAccountName: elasticsearch-logging
      securityContext:
        fsGroup: 1000
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-logging-init
        securityContext:
          privileged: true
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
        name: elasticsearch-logging
        resources:
          limit:
            cpu: 100m
            memory: 3Gi
          requests:
            cpu: 100m
            memory: 3Gi
        securityContext:
          privileged: true
          runAsUser: 1000
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-logging-storage
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-logging-yml
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        env:
        - name: ES_JAVA_OPTS
          valueFrom:
              configMapKeyRef:
                  name: elasticsearch-logging-config
                  key: ES_JAVA_OPTS
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
      volumes:
        - name: elasticsearch-logging-yml
          configMap:
            name: elasticsearch-logging-config
            items:
                - key: elasticsearch.yml
                  path: elasticsearch.yml
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-logging-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default
      resources:
        requests:
          storage: 50Gi