apiVersion: apps/v1
kind: Deployment
metadata:
  name: dc-grafana-deployment
  namespace: collectors
  labels:
    app: dc-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dc-grafana
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: dc-grafana
    spec:
      containers:
      - name: dc-grafana
        image: smartemission/se-grafana-dc:5.1.3-2
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          timeoutSeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          timeoutSeconds: 30
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: dc-grafana
              key: username
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dc-grafana
              key: password
        - name: SE_INFLUX_DC1_URL
          value: "http://dc-airsenseur:8086"
        - name: GF_SERVER_ROOT_URL
          value: "%(protocol)s://%(domain)s:%(http_port)s/grafana-dc"
        - name: SE_INFLUX_USER
          valueFrom:
            secretKeyRef:
              name: dc-airsenseur-reader
              key: username
        - name: SE_INFLUX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dc-airsenseur-reader
              key: password 
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"