apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: waalkade-deployment
  namespace: smartemission
  labels:
    app: waalkade
spec:
  replicas: 2
  selector:
    matchLabels:
      app: waalkade
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: waalkade
    spec:
      containers:
      - name: waalkade
        image: smartemission/se-waalkade:latest
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 80