apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mosquitto-deployment
  namespace: smartemission
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: smartemission/se-mosquitto:latest
        ports:
        - containerPort: 1883