apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etl-rivm-harvester
  namespace: smartemission
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etl-rivm-harvester
            image: smartemission/se-stetl:1.0.14
            args:
            - harvester_rivm
            env:
            - name: stetl_rivm_sos_base_url
              value: "http://inspire.rivm.nl/sos/eaq/api/v1/timeseries/"
            - name: stetl_max_proc_time_secs
              value: "660"
            - name: stetl_api_interval_secs
              value: "-1"
            - name: stetl_pg_host
              value: "postgres"
            - name: stetl_pg_database
              value: "gis"
            - name: stetl_pg_user
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: stetl_pg_password
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: stetl_pg_schema_raw
              value: "smartem_raw"
            - name: stetl_pg_schema_harvest_rivm
              value: "smartem_harvest_rivm"
            - name: stetl_influx_host
              value: "influxdb-service"
            - name: stetl_influx_port
              value: "8086"
            - name: stetl_influx_se_database
              value: "smartemission"
            - name: stetl_influx_se_measurement_refined
              value: "joserefined"
            - name: stetl_influx_se_writer
              valueFrom:
                secretKeyRef:
                  name: influxdb-writer
                  key: username
            - name: stetl_influx_se_writer_password
              valueFrom:
                secretKeyRef:
                  name: influxdb-writer
                  key: password         
          restartPolicy: OnFailure