apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etl-sos-publisher
  namespace: smartemission
spec:
  schedule: "*/12 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etl-sos-publisher
            image: smartemission/se-stetl:1.0.13
            args:
            - sospublisher
            env:
            - name: stetl_pg_host
              value: "postgres"
            - name: stetl_pg_database
              value: "gis"
            - name: stetl_pg_user
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: stetl_pg_password
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: stetl_pg_schema_refined
              value: "smartem_refined"
            - name: stetl_sospublisher_max_input_records
              value: "1200"
            - name: "stetl_sos_host"
              value: "sos52n-service"
            - name: "stetl_sos_port"
              value: "8080"
            - name: "stetl_sos_path"
              value: "/sos52n/service"
          restartPolicy: OnFailure