apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etl-extractor
  namespace: smartemission
spec:
  schedule: "*/20 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etl-extractor
            image: smartemission/se-stetl:1.0.20
            args:
            - extractor
            env:
            - name: stetl_extractor_max_input_records
              value: "2000"
            - name: stetl_extractor_raw_read_once
              value: "True"
            - name: stetl_pg_host
              value: "postgres"
            - name: stetl_pg_database
              value: "gis"
            - name: stetl_pg_user
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: stetl_pg_password
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: stetl_pg_schema_raw
              value: "smartem_raw"
            - name: stetl_pg_schema_refined
              value: "smartem_refined"
            - name: stetl_pg_schema_extracted
              value: "smartem_extracted"
            - name: stetl_influx_host
              value: "influxdb-service"
            - name: stetl_influx_port
              value: "8086"
            - name: stetl_influx_se_database
              value: "smartemission"
            - name: stetl_influx_se_measurement_extract
              value: "joseextract"
            - name: stetl_influx_se_writer
              valueFrom:
                secretKeyRef:
                  name: influxdb-writer
                  key: username
            - name: stetl_influx_se_writer_password
              valueFrom:
                secretKeyRef:
                  name: influxdb-writer
                  key: password    
          restartPolicy: OnFailure