apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etl-influxdb-harvester
  namespace: smartemission
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etl-influxdb-harvester
            image: smartemission/se-stetl:1.0.17
            args:
            - harvester_influx
            env:
            - name: stetl_influx_dc1_host
              value: "dc1.smartemission.nl"
            - name: stetl_influx_port
              value: "8086"
            - name: stetl_influx_as_database
              value: "airsenseur"
            - name: stetl_influx_as_reader
              valueFrom:
                secretKeyRef:
                  name: influxdb-reader
                  key: username
            - name: stetl_influx_as_reader_password
              valueFrom:
                secretKeyRef:
                  name: influxdb-reader
                  key: password         
            - name: stetl_max_proc_time_secs
              value: "660"
            - name: stetl_pg_host
              value: "postgres"
            - name: stetl_pg_database
              value: "gis"
            - name: stetl_pg_user
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: stetl_pg_password
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: stetl_pg_schema_raw
              value: "smartem_raw"
          restartPolicy: OnFailure