apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etl-refiner
  namespace: smartemission
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etl-refiner
            image: smartemission/se-stetl:1.0.1
            args:
            - refiner
            env:
            - name: stetl_refiner_max_input_records
              value: "4000"
            - name: stetl_refiner_raw_read_once
              value: "true"
            - name: stetl_pg_host
              value: "postgres"
            - name: stetl_pg_database
              value: "gis"
            - name: stetl_pg_user
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: stetl_pg_password
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: stetl_pg_schema_raw
              value: "smartem_raw"
            - name: stetl_pg_schema_refined
              value: "smartem_refined"
            - name: stetl_pg_schema_calibrated
              value: "smartem_calibrated"
          restartPolicy: OnFailure