apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sos52n-deployment
  namespace: smartemission
  labels:
    app: sos52n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sos52n
  template:
    metadata:
      labels:
        app: sos52n
    spec:
      containers:
      - name: sos52n
        image: smartemission/se-sos52n:latest
        env:
          - name: SOS_USERNAME
            valueFrom:
              secretKeyRef:
                name: sos52n
                key: username
          - name: SOS_PASSWD
            valueFrom:
              secretKeyRef:
                name: sos52n
                key: password
          - name: DB_HOSTNAME
            value: "postgres"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres
                key: username
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: DB_SCHEMA
            value: "sos52n1"
        ports:
        - containerPort: 8080